-- get all databases present in shcemas
show databases;
select *from rgmcet;

-- updation of column
update rgmcet set student_name="SPANDANA" where student_contact =9999;

update rgmcet set student_session="FSD" ,student_address = "NANDYAL" where student_contact =96895;

select *from student;
-- creation of table with same columns of copying table
create table test(stu_id int primary key not null,stu_name varchar(30),stu_marks int);
-- copy of table to anther empty table with same columns
insert into test select *from student;
-- delete data in test table
truncate table test;
select *from test;
select * from student;
-- delete entire row
delete from student where student_name ="SWETHA";

-- deletion of table
drop table test;
select *from student;
-- remane the old column name to new name
alter table student rename column student_name to name;
select *from student;
-- changing of name
alter table student rename to rgm_student;
select * from rgm_student;

CREATE DATABASE SS;
SHOW DATABASES;
-- TO DROP THE DATABASE
DROP DATABASE SS;
select * from rgm_student;
-- Addition of column
ALTER TABLE rgm_student ADD address VARCHAR(40);
-- add data to added column
UPDATE rgm_student SET address = "BATHALUR" WHERE student_id=101;
-- TO SEE THIS CHANGE GO TO TABLE NAME CLICK ON 1 SYMBOL AND THE COLUMS 
ALTER TABLE rgm_student MODIFY COLUMN address VARCHAR(50);-- ALTER DATATYPE OR SIZE
-- DROP ANY PERTICULAR COLUMN
ALTER TABLE rgm_student DROP COLUMN address;

select * from rgm_student;

ALTER TABLE rgm_student DROP COLUMN address,drop column name ;
ALTER TABLE rgm_student ADD marks int;

UPDATE rgm_student SET marks= 90 WHERE student_id=101;
UPDATE rgm_student SET marks= 45 WHERE student_id=102;
UPDATE rgm_student SET marks= 97 WHERE student_id=104;
UPDATE rgm_student SET marks= 88 WHERE student_id=105;
UPDATE rgm_student SET marks= 65 WHERE student_id=107;

SELECT MAX(MARKS) FROM rgm_student;-- TO GET MAX MARKS
SELECT AVG(MARKS) FROM rgm_student;-- TO  GET AVERAGE 
SELECT SUM(MARKS) FROM rgm_student;-- TO GET SUM
SELECT SUM(MARKS) AS TOTAL FROM rgm_student; -- to change the column name in outut

CREATE DATABASE EXERCISE;
CREATE TABLE CUSTOMER(CUS_ID INT ,CUS_NAME VARCHAR(40),CITY VARCHAR(30),GRADE INT,SALESMAN_ID INT);
SELECT * FROM CUSTOMER;
INSERT INTO CUSTOMER VALUES(101,'SUMANTH','DELHI',98,201),
(102,'SWAPNA','HYD',97,202),(103,'SWATHI','KERALA',77,203),
(142,'CHITTI','KADAPA',67,204),(105,'SWETHA','NANDYAL',88,205),
(106,'PREETHI','CHENNAI',79,206),(107,'SPANDANA','BANGALORE',87,207),(108,'SUNANDHA','PUNJOB',78,208);
INSERT INTO CUSTOMER VALUES(109,'SAMRIN','ALLAGADDA',68,209),(110,'SUMANA','ANANTHAPUR',99,210);
-- WRITE A SQL QUERY TO FIND THE DETAILS OF THE CUSTOMER WHOSE GRADE ARE ABOVE 90
SELECT * FROM CUSTOMER WHERE GRADE > 90;
-- WRITE A SQL QUERY TO FIND THE DETAILS OF THE CUSTOMER WHOSE GRADE ARE ABOVE  AND EQUAL TO88
SELECT * FROM CUSTOMER WHERE GRADE >= 88;
-- WRITE A SQL QUERY TO FIND THE DETAILS OF THE CUSTOMER WHOSE GRADE ARE ABOVE  AND EQUAL TO88

SELECT * FROM CUSTOMER WHERE GRADE >= 88 ORDER BY GRADE;
SELECT * FROM CUSTOMER WHERE GRADE >= 88 ORDER BY  GRADE ASC;
-- WRITE A SQL QUERY TO FIND THE DETAILS OF THE CUSTOMER WHOSE GRADE ,=100 AND CITY IS HYD
SELECT* FROM CUSTOMER WHERE  CITY='HYD' AND GRADE<=100;
SELECT* FROM CUSTOMER WHERE  CITY='HYD' AND GRADE>90;
-- WRITE A SQL QUERY TO FIND THE DETAILS OF THE CUSTOMER NAME WHO ARE FROM HYD OR GRADE >100
SELECT * FROM CUSTOMER WHERE CITY='HYD' OR GRADE >90;
-- WRITE A SQL QUERY TO FIND THE DETAILS OF THE CUSTOMER WHO ARE EITHER FROM KERALA OR WHO DO NOT HAVE A GRADE >100
SELECT *FROM CUSTOMER WHERE  CITY='KERALA' OR NOT GRADE  >90;
-- WRITE A SQL QUERY TO IDENTIFY THE CUSTOMER WHO DO NOT BELONG TO THE CITY KERALA OR HAVE A GRADE THAT EXCEEDS 80
-- FIND THE ORDER DETAILS EXCUDING THE DATE 30-4-23 AND SALESMAN ID MORE THA 200 AND PURCHASE AMOUNT 1000
CREATE TABLE ORDERS(
ORDER_NUM INT,PURCHASE_AMT INT,ORDER_DATE DATE,CUS_ID INT,SALESMAN_ID INT);
INSERT INTO ORDERS VALUES( 2002,1000,'2023-04-23',100,200),( 2003,1100,'2023-04-23',101,201),( 2004,1200,'2023-04-30',102,203),( 2004,1300,'2023-05-25',104,204),
( 2005,1400,'2003-05-27',105,205);
SELECT * FROM ORDERS WHERE NOT ORDER_DATE = '2023-04-30' AND SALESMAN_ID > 202 OR PURCHASE_AMT>1200;
CREATE TABLE SALESMAN(
SALESMAN_ID INT PRIMARY KEY,NAME VARCHAR(60),CITY VARCHAR(53),commission float);
SELECT * FROM SALESMAN;
INSERT INTO SALESMAN VALUES(200,'SWAPNA','KURNOOL',0.45),
(201,'SWATHI','NANDYAL',0.5),(202,'CHITTI','KADAPA',0.230),
(240,'PREETHI','HYD',0.75);
-- TO FIND SALESMAN DETAILS WHOSE COMMISSION ARE WIYH IN THE RANGE FROM 0.23 TO O.43
SELECT * FROM SALESMAN WHERE COMMISSION BETWEEN 0.23 AND 0.43;
-- TO FIND SALESMAN DETAILS WHOSE NAME STARTS WITH K LETTER
SELECT * FROM SALESMAN WHERE NAME LIKE 'K%';
-- CREATE A NEW COLUMN ADDRESS INSERT SOME DATA IN THAT COLUMN AND DISPLAY ALTHOSE IN DEC ORDER
ALTER TABLE SALESMAN ADD ADDRESS VARCHAR(30);
SELECT * FROM SALESMAN ;

UPDATE SALESMAN SET ADDRESS='HYD' WHERE NAME='SWAPNA';
UPDATE SALESMAN SET ADDRESS='NDL' WHERE NAME='SWATHI';
UPDATE SALESMAN SET ADDRESS='KADAPA' WHERE NAME='CHITTI';
UPDATE SALESMAN SET ADDRESS='BAGL' WHERE NAME='PREETHI';
SELECT * FROM SALESMAN ORDER BY ADDRESS DESC;
-- CREATE A NEW COLUMN ADDRESS INSERT SOME DATA IN THAT COLUMN AND DISPLAY ALTHOSE AS SALESMAN ADDRESS IN DEC ORDER
SELECT ADDRESS AS SALESMAN_ADDRESS FROM SALESMAN ORDER BY ADDRESS DESC;
